import { StyleSheet } from "react-native";

const globalStyles = StyleSheet.create({
	container: {
		padding: 20,
		backgroundColor: "#fff",
		flex: 1,
	},
	inputContainer: {
		fontSize: 16,
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 10,
		padding: 10,
		backgroundColor: "#fff",
	},
	submitButton: {
		backgroundColor: "#FFBF18",
		borderRadius: 15,
		paddingVertical: 15,
		width: 165,
		marginBottom: 10,
	},
	inactivityButton: {
		borderColor: "#FFBF189E",
		backgroundColor: "#fff",
		borderRadius: 15,
		paddingVertical: 17,
		width: 165,
		marginBottom: 10,
		borderWidth: 1,
	},
	submitButtonText: {
		textAlign: "center",
		color: "#fff",
		fontWeight: "bold",
		fontSize: 16,
	},
	inactivityButtonText: {
		textAlign: "center",
		color: "#FFBF189E",
		fontWeight: 500,
		fontSize: 16,
	},
	cardContainer: {
		paddingHorizontal: 26,
		paddingVertical: 15,
		// borderRadius: 10,
		backgroundColor: "#fff",
		borderRadius: 20,
		borderColor: "#ddd",
		borderWidth:1
		// elevation: 5,
	},
	cardBody: {
		paddingHorizontal: 0,
		paddingVertical: 0,
	},
	sectionHeader: {
		backgroundColor: "#e8f0ff",
		width: "100%",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		paddingHorizontal: 26,
		paddingVertical: 15,
		color: "#000",
		fontWeight: 500,
	},
	contentPadding: {
		paddingHorizontal: 26,
		paddingVertical: 15,
	},
	textLabel: {
		fontSize: 15,
		color: "#000",
		fontWeight: "bold",
	},
	text1: {
		fontSize: 16,
		lineHeight: 28,
		color: "#1F1F1F",
		fontWeight: "500",
	},
	title: {
		fontSize: 14,
		lineHeight: 44,
		color: "#1F1F1F",
		fontWeight: "400",
	},
	label: {
		fontSize: 12,
		lineHeight: 15,
		color: "#1F1F1F",
		fontWeight: "300",
	},
	textInputContainer: {
		borderWidth: 1,
		borderColor: "#ddd",
		borderRadius: 10,
		paddingHorizontal: 10,
		fontSize: 16,
	},
	divider: {
		borderTopWidth: 1,
		borderColor: "#82828257",
		marginHorizontal: -10,
	},
	errorText: {
		color: "red",
		fontSize: 12,
		marginTop: 4,
		marginLeft: 4,
	},
	submitWrapper: {
		position: "absolute",
		bottom: 50,
		left: 20,
		right: 20,
		width: "100%",
		justifyContent: "center",
	},
	cardContainer1: {
		borderWidth: 1,
		borderColor: "#ddd",
		margin: 20,
		padding: 20,
		borderRadius: 20,
		backgroundColor: "#fff",
		gap: 15,
	},
	text2: {
		color: "#888",
		fontSize: 12,
		lineHeight: 14,
	},
	image: {
		width: 300,
		height: 300,
		margin: 20,
		alignSelf: "center",
		top: -50,
	},
	line1: {
		// left: 5,
		fontSize: 20,
		fontWeight: 500,
		textAlign: "center",
		top: -80,
	},
	line2: {
		fontSize: 14,
		fontWeight: 300,
		textAlign: "center",
		top: -60,
		lineHeight: 20,
	},
});

export default globalStyles;
